apiVersion: apps/v1
kind: Deployment
metadata:
  name: travellist-app
  labels:
    app: travellist-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: travellist-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: travellist-app
    spec:
      containers:
      - name: travellist-app
        image: "{{ image_id }}"
        ports:
          - containerPort: 80
        envFrom:
          - configMapRef:
              name: travellist-config
      imagePullSecrets:
        - name: nexus-docker
