apiVersion: v1
kind: Service
metadata:
  name: travellist-app-service
spec:
  selector:
    app: travellist-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000