- hosts: all
  vars_files: 
    - "vars/{{ env }}.yml"
  tasks:
  - name: Deploy the service
    k8s:
      state: present
      definition: "{{ lookup('template', 'templates/secret.yaml') | from_yaml }}"
      validate_certs: no
      namespace: default
  - name: Deploy the service
    k8s:
      state: present
      definition: "{{ lookup('template', 'templates/nexus-docker.yaml') | from_yaml }}"
      validate_certs: no
      namespace: default
  - name: Deploy the service
    k8s:
      state: present
      definition: "{{ lookup('template', 'templates/mysql-pv.yaml') | from_yaml }}"
      validate_certs: no
      namespace: default
  - name: Deploy the service
    k8s:
      state: present
      definition: "{{ lookup('template', 'templates/configmap.yaml') | from_yaml }}"
      validate_certs: no
      namespace: default
  - name: Deploy the service
    k8s:
      state: present
      definition: "{{ lookup('template', 'templates/deployment.yaml') | from_yaml }}"
      validate_certs: no
      namespace: default
  - name: Deploy the service
    k8s:
      state: present
      definition: "{{ lookup('template', 'templates/deploymentSQL.yaml') | from_yaml }}"
      validate_certs: no
      namespace: default
  - name: Deploy the service
    k8s:
      state: present
      definition: "{{ lookup('template', 'templates/ingress.yaml') | from_yaml }}"
      validate_certs: no
      namespace: default