- hosts: all
  vars_files: 
    - "vars/{{ env }}.yml"
  tasks:
  - name: Deploy the service
    k8s:
      state: present
      validate_certs: no
      namespace: default
      definition: "{{ lookup('template', '{{ item }}') | from_yaml }}"
   with_items:
         - templates/secret.yaml
         - templates/nexus-docker.yaml
         - templates/mysql-pv.yaml
         - templates/configmap.yaml
         - templates/deployment.yaml
         - templates/deploymentSQL.yaml
         - templates/ingress.yaml
  